CREATE TABLE INSTR1
(
    SICOVAM NUMBER(10) NOT NULL,
    TYPE_ VARCHAR2(50),
	NOTIONAL NUMBER(20,5)
)
|||
CREATE TABLE INSTR2
(
    SICOVAM NUMBER(10) NOT NULL,
    TYPE_ VARCHAR2(50),
	NOTIONAL NUMBER(20,5)
)
